### ISSUE TITLE
ASAP does not guarantee next tick behaviour

### ISSUE THREAD

**Issue by allain** [RangerMauve/call-later#1]
internally asap module can use setImmediate instead of process.nextTick, which would place the code to be called before the next tick possibly even before the last event in the queue (I think it would proceed io events).

**Comment by RangerMauve** [comment]
Good point. Would just a setTimeout be better, then?

**Comment by allain** [comment]
I believe so, or process.nextTick in node.js

**Comment by RangerMauve** [comment]
Actually, I think that I could live with that. As long as it's happening asynchronously, it's good enough for me. If anyone runs into any issues with this in the wild I'll change it.
